### ISSUE TITLE
请问实现原理是什么？

### ISSUE THREAD

**Issue by sogud** [0xe69e97/vite-demo#2]

**Comment by 0xe69e97** [comment]
手写的这个版本主要实现了

处理 HTML 文件
处理 JSX 文件
处理 CSS 文件
处理 SVG 文件
通过 ESBuild 打包

来学习 Vite 的思路，并没有完全演示 Vite 如果需要可以去看一下 Vite 的[源码](https://github.com/vitejs/vite)
